#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := wemos_drapes

EXTRA_COMPONENT_DIRS := ${IDF_ESP8266_PATH}/../../iot-core

include $(IDF_ESP8266_PATH)/make/project.mk

